# The `Create` message of a need must not contain a reference
prefix msg: <https://w3id.org/won/message#>
select ?msg where {
  ?msg msg:hasMessageType msg:CreateMessage;
	   msg:hasPreviousMessage ?msg.
}

